name: 🚀 New device request
description: A request for a new device to be supported by HeadsetControl
labels: [device-request]
body:
- type: markdown
  attributes:
    value: |
      Thank you for your input!  
      
      **Note**: Probably only people with the same device can help to implement the protocol for it
      That is why it is a good idea to try it yourself 🚀! Take a look at the [Wiki](https://github.com/Sapd/HeadsetControl/wiki/Development).
      
      We are here to help you. You can provide WireShark logs, ask for help in Coding and open up a PR any time.
- type: input
  id: device
  attributes:
    label: Headset Name
    description: Manufacturer and name of the headset
    placeholder: ex. Corsair HS80
  validations:
    required: true
- type: textarea
  id: description
  attributes:
    label: Description
    description: Type in all details which could be useful
  validations:
    required: true

- type: dropdown
  id: browsers
  attributes:
    label: Which OS do you use?
    multiple: false
    options:
    - Linux
    - MacOS
    - Windows
- type: textarea
  id: deviceinfo
  attributes:
    label: Device information
    description: Please copy and paste below (replacing *PASTE HERE*) the output of the command `headsetcontrol --dev -- --list` . If you have a deviceid, use `headsetcontrol --dev -- --list --device VENDORID:DEVICEID` instead please.
    value: |
        <details>
         <summary>Device IDs</summary>
  
         ```
         PASTE HERE
         ```
  
        </details>
